// src/lib/components/ArticleCard.svelte
<script lang="ts">
  export let title: string;
  export let summary: string;
  export let source: string;
  export let url: string;
  export let publishedAt: Date;
</script>

<a href={url} class="block hover:bg-gray-50">
  <div class="px-4 py-4 sm:px-6">
    <div class="flex items-center justify-between">
      <h2 class="text-lg font-medium text-indigo-600 truncate">
        {title}
      </h2>
      <div class="ml-2 flex-shrink-0 flex">
        <p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
          {source}
        </p>
      </div>
    </div>
    <div class="mt-2">
      <p class="text-sm text-gray-500">
        {summary}
      </p>
    </div>
  </div>
</a>

// components/ArticleCard.tsx
import Image from 'next/image';
import { Article, Source } from '@prisma/client';

interface ArticleCardProps {
  article: Article & {
    source: Source;
  };
}

export function ArticleCard({ article }: ArticleCardProps) {
  return (
    <div className="rounded-lg border bg-card text-card-foreground shadow">
      {article.imageUrl && (
        <div className="relative h-48 w-full">
          <Image
            src={article.imageUrl}
            alt={article.title}
            fill
            className="object-cover rounded-t-lg"
          />
        </div>
      )}
      <div className="p-4">
        <div className="flex items-center gap-2 text-sm text-muted-foreground">
          <span>{article.source.name}</span>
          <span>•</span>
          <time dateTime={article.publishedAt.toISOString()}>
            {new Date(article.publishedAt).toLocaleDateString()}
          </time>
        </div>
        <h3 className="text-lg font-semibold mt-2">
          <a href={article.url} target="_blank" rel="noopener noreferrer">
            {article.title}
          </a>
        </h3>
        {article.summary && (
          <p className="mt-2 text-muted-foreground">{article.summary}</p>
        )}
      </div>
    </div>
  );
}
